
const users = [
  {
    lastName: 'Peter',
    email: 'peter@gmail.com',
    password: '12345678',
    gender: 'F',
    jobRole: 'Accountant',
    department: 'Accounting',
    address: 'Kigali, Rwanda',
  },
  {
    firstName: ' ',
    lastName: 'John',
    email: 'john@gmail.com',
    password: 'hjgfsdbvm',
    gender: 'M',
    jobRole: 'IT specialist',
    department: 'IT',
    address: 'Kampala, Uganda',
  },
  {
    firstName: '9999',
    lastName: 'Rene',
    email: 'rene@gmail.com',
    password: 'nmoptyifg',
    gender: 'F',
    jobRole: 'Software Developer',
    department: 'Software development',
    address: 'Nairobi, Kenya',
  },
  {
    firstName: 'NDACYAYISABA',
    lastName: 'Samuel',
    email: 'samuel@gmail.com',
    password: 'Samuel@123',
    gender: 'FF',
    jobRole: 'Chef',
    department: 'Curinaly arts',
    address: 'Kicukiro, Gikondo',
  },
  {
    firstName: 'Kiza',
    lastName: 'sylvain',
    email: 'sylvain@gmail.com',
    password: 'sylvain8937',
    gender: 'M',
    jobRole: 'Desisgner',
    department: 'Multimedia',
    address: 'Nyarugenge, Kimisagara',
  },
  {
    firstName: 'NSABIMANA',
    lastName: 'Valency',
    email: 'valency@yahoo.com',
    password: 'Valency8993',
    gender: 'F',
    jobRole: 'carpenter',
    department: 'Construction',
    address: 'Gasabo,Kimironko',
  },
  {
    password: 'mxcaqwspoy',
  },
  {
    email: 'sylvain@gmail.com',
    password: 'password',
  },
  {
    email: 'user@gmail.com',
    password: '9746hdn547',
  },
];

export default users;
